// Modules precompiled header.
#pragma once

#if defined(USE_MODULE_CPPTOOLS) && (USE_MODULE_CPPTOOLS == USE_MODULE_AS_PRECOMPILED_SOURCES OR USE_MODULE_CPPTOOLS == USE_MODULE_FULL_SOURCES)
#	include "CppTools/CppToolsModule.hxx"
#endif

#if defined(USE_MODULE_ENVIRO) && (USE_MODULE_ENVIRO == USE_MODULE_AS_PRECOMPILED_SOURCES OR USE_MODULE_ENVIRO == USE_MODULE_FULL_SOURCES)
#	include "Enviro/EnviroModule.hxx"
#endif

#if defined(USE_MODULE_WINTOOLS) && (USE_MODULE_WINTOOLS == USE_MODULE_AS_PRECOMPILED_SOURCES OR USE_MODULE_WINTOOLS == USE_MODULE_FULL_SOURCES)
#	include "WinTools/WinToolsModule.hxx"
#endif

#if defined(USE_MODULE_MAPITOOLS) && (USE_MODULE_MAPITOOLS == USE_MODULE_AS_PRECOMPILED_SOURCES OR USE_MODULE_MAPITOOLS == USE_MODULE_FULL_SOURCES)
#	include "MapiTools/MapiToolsModule.hxx"
#endif

#if defined(USE_MODULE_WINSOCKETS) && (USE_MODULE_WINSOCKETS == USE_MODULE_AS_PRECOMPILED_SOURCES OR USE_MODULE_WINSOCKETS == USE_MODULE_FULL_SOURCES)
#	include "WinSockets/WinSocketsModule.hxx"
#endif

#if defined(USE_MODULE_ZIPTOOLS) && (USE_MODULE_ZIPTOOLS == USE_MODULE_AS_PRECOMPILED_SOURCES OR USE_MODULE_ZIPTOOLS == USE_MODULE_FULL_SOURCES)
#	include "ZipTools/ZipSocketsModule.hxx"
#endif
