#if defined(USE_MODULE_CPPTOOLS) && (USE_MODULE_CPPTOOLS == USE_MODULE_AS_PRECOMPILED_SOURCES OR USE_MODULE_CPPTOOLS == USE_MODULE_FULL_SOURCES)
#	include "CppToolsModule.cpp"
#	include "XError.cpp"
#endif
